server:
  port: 8081 #8181
spring:
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/zentao?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapperLocations: mappers/*mapper.xml
  
datasource:
  item:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: test1
    driver-class-name: com.mysql.jdbc.Driver
  product:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
    username: root
    password: test1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect